apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudnativebasicspring-deployment
spec:
  selector:
    matchLabels:
      app: cloudnativebasicspring
  replicas: 5
  template:
    metadata:
      labels:
        app: cloudnativebasicspring
    spec:
      containers:
      - name: cloudnativebasicspring
        image: fharris/cloudnativebasic-spring-docker:latest
        ports:
        - containerPort: 8080
