apiVersion: v1
kind: Service
metadata:
  name: cloudnativebasicspring-service
  annotations:
    oci.oraclecloud.com/load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: cloudnativebasicspring
